### ISSUE TITLE
Help - jsreport-core with jsreport-express

### ISSUE THREAD

**Issue by gustavomassa** [jsreport/jsreport-express#10]
Hello,

I'm trying to initialize the jsreport-express, the api seems to be working, but the studio interface does not load, I've tried different routes and options.
The studio is the user panel interface right?

here is my example:
The WBA is my framework, you can use express directly as an example with https server.
```
import * as fs from 'fs';
import * as express from 'express';
import jsreportCreator = require('jsreport-core');

export class ReportController {
    private static _instance: ReportController;
    private jsreport: jsreportCreator.Reporter;
    private reportingApp: express.Application;
    private reportingRoute: string;

    public static get Instance(): ReportController {
        return this._instance || (this._instance = new this());
    }

    private constructor() {
        const options: any = { templatingEngines: { strategy: 'in-process' } };
        this.jsreport = jsreportCreator(options);
        this.reportingApp = express();
        this.reportingRoute = '/api/v1/reporting';
        WBA.rest().express.use(this.reportingRoute, this.reportingApp);
    }

    public async init(): Promise<void> {
        const options = {
            extensions: {
                express: { app: this.reportingApp, server: WBA.server().$httpsServer },
            },
            appPath: this.reportingRoute,
            //mountOnAppPath: true
        };

        this.jsreport.use(require('jsreport-templates')());
        this.jsreport.use(require('jsreport-data')());
        this.jsreport.use(require('jsreport-resources')());
        //this.jsreport.use(require('jsreport-images')());
        this.jsreport.use(require('jsreport-handlebars')());
        this.jsreport.use(require('jsreport-chrome-pdf')());
        this.jsreport.use(require('jsreport-phantom-pdf')());
        //this.jsreport.use(require('jsreport-debug')());
        this.jsreport.use(require('jsreport-express')(options));

        //await this.jsreport.init();

        //This render example works fine too
        this.jsreport.init().then(() => {
            return this.jsreport.render({
                template: {
                    content: '<h1>Hello {{foo}}</h1>',
                    engine: 'handlebars',
                    recipe: 'chrome-pdf'
                },
                data: {
                    foo: "world"
                }
            }).then((resp) => {
                //console.log(resp.content.toString())
                fs.writeFileSync('report.pdf', resp.content);
            });
        }).catch((e) => {
            console.error(e)
        });
		
        //This works fine using jsreport instead of jsreport-core
       //const jsreport = require('jsreport')({express: {app: this.reportingApp }});
      //await jsreport.init();  */
    }

}
```

**Comment by pofider** [comment]
Why don't you use jsreport package directly?

**Comment by gustavomassa** [comment]
Because I would like to have control about all the modules/extensions, also I would like to use the minimal package that has core + api + studio(user interface).

**Comment by pofider** [comment]
You are missing `jsreport-studio` in the used extension.
Not sure now if it is enough, but definitely needed.

**Comment by pofider** [comment]
So something like this is missing.

```js
this.jsreport.use(require('jsreport-studio')());
```

Hope this helps. Feel free continue comments.

**Comment by gustavomassa** [comment]
hmm, I did not know about jsreport-studio package, the jsreport-core readme references jsreport-express as studio.
I installed jsreport-studio and used it on the jsreport like this: 
`this.jsreport.use(require('jsreport-studio')());`

This is the options I'm using, I've tried using mountOnAppPath as true and false, but no lucky yet. My https server is port 2000 and appPath references to '/api/v1/reporting'
Log: `2018-07-31T13:46:30.498Z [Master PID 11680] info: - GET 1.1 /api/v1/reporting/ - Status: 404 Time: 2.583 ms - -`
```
const options = {
                extensions: {
                    express: { app: this.reportingApp, server: WBA.server().$httpsServer },
                },
                appPath: this.reportingRoute,
                mountOnAppPath: true
            };
```

I'm debugging jsreport-core extenstionsManager, the studio is being loaded correctly:
![image](https://user-images.githubusercontent.com/16235598/43464809-5be2d8b2-94b2-11e8-8703-2733b51ac042.png)

It seems that jsreport-studio routes/static files are not being loaded. Any ideas or functions that I can use to manually load them?

**Comment by gustavomassa** [comment]
![image](https://user-images.githubusercontent.com/16235598/43467172-847a791a-94b7-11e8-97db-d9d614344658.png)
Maybe the studio is using the wrong express app instance. I will try to add some unique identifier to the reportingApp, and make sure the studio is using that instance and not initializing a new express app internally.

**Comment by gustavomassa** [comment]
There is a bug on line 214 of jsreport-express reporter.express.js:
```
 let app = definition.options.app
  if (!app) {
    app = require('express')()
  }
```

The definition.options.app does not exists, it should be: definition.options.extensions.express.app
So internally jsreport is always creating a new instance of express app even if we pass it through options object.
The option object should have the extension property? or should have the name of the extension directly on the root of the options object?
![image](https://user-images.githubusercontent.com/16235598/43473706-49a7bb4e-94c7-11e8-90b1-b5871148024e.png)
fix: 
`let app = (definition.options && definition.options.extensions && definition.options.extensions.express && definition.options.extensions.express.app) ? definition.options.extensions.express.app : null;`

Now the routes are working fine and the jsreport-studio is loading, but it is not finding the static files, I think the server passed on the options object is not being used correctly.

**Comment by bjrmatos** [comment]
> hmm, I did not know about jsreport-studio package, the jsreport-core readme references jsreport-express as studio.

thanks again, i updated the README to mention both studio and express package.



> There is a bug on line 214 of jsreport-express reporter.express.js:

i think your problem is different. when you use jsreport-core and manually use extensions then the way of passing configuration works in other way, for example there are two ways of pass configuration: 

- you can do it by passing all the configuration that you need in single options object to the jsreport-core constructor (this is know as **global configuration**), this object can contain a shape like this: 

```js
{
  templatingEngines: { strategy: 'in-process' },
  extensions: {
    express: { app: this.reportingApp, server: WBA.server().$httpsServer },
  },
  appPath: this.reportingRoute,
  mountOnAppPath: true
}
```

(note how you can pass configuration to specific extensions, for example in this case what you put in `extensions.express` will be the same that passing those values to the jsreport-express constructor when you call `.use()`)

specifically in your code you can pass all the configuration in single object here: `this.jsreport = jsreportCreator(options);` 

- you can do it by passing options object to each extensions constructor, for example in the case of express extension you should pass your options like this:

```js
this.jsreport.use(require('jsreport-express')({ 
  appPath: this.reportingRoute,
  mountOnAppPath: true,
  app: this.reportingApp, 
  server: WBA.server().$httpsServer
}))
```

right now you are passing an object which contains `extensions` keys, but that format is not expected for the options of the jsreport-express constructor, what is expected there are the values only relevant for the specific extension.

now i will add a reference to the docs in order to clarify options like `appPath`, `mountOnAppPath`:

>jsreport-express uses some options from the global configuration:
.....
httpPort (number) - http port on which is jsreport running, if both httpPort and httpsPort are specified, jsreport will automaticaly create http redirects from http to https, if any of httpPort and httpsPort is specified default process.env.PORT will be used
.....
httpsPort (number) - https port on which jsreport is running
.....
appPath (string) - optionally set application path, if you run application on http://appdomain.com/reporting then set "/reporting" to appPath. The default behavior is that it is assumed that jsreport is running behind a proxy, so you need to do url url rewrite /reporting -> / to make it work correctly, See mountOnAppPath when there is no proxy + url rewrite involved in your setup.
.....
mountOnAppPath (boolean) - use this option along with appPath. it specifies if all jsreport routes should be available with appPath as prefix, therefore making appPath the new root url of application
certificate object - path to key and cert file used by https

by default each extensions will only get values defined in `extensions` object or values passed directly to its constructor when using `.use()`. however there are extensions like jsreport-express that supports reading values from top level configuration (**global configuration**) so for example express configuration like `appPath`, `mountOnAppPath` can be passed directly like this in jsreport-core constructor (it does not need that those values live inside `extensions` object):

```js
this.jsreport = jsreportCreator({
  appPath: '...',
  mountOnAppPath: true,
  extensions: {...}
});
```

this is why the README mentions the following: `jsreport-express uses some options from the global configuration` and list the configuration properties that are supported as top level keys.

hope it helps you.

**Comment by gustavomassa** [comment]
@bjrmatos  thank you! you are right! I was passing configuration using the extensions property to jsreport extensions packages, now passing an entire configuration object as global configuration to jsreport-core works fine.
I have one more question regarding logger option and two errors to report:

1. My framework also uses winston with three transport methods, I'm trying to pass the transport list to jscore using the logger property:
```
//transport method list:
this.consoleTransport = new (transports.Console)(
    {
        level: 'debug',
        handleExceptions: true,
        prettyPrint: true,
        colorize: true
    }
);
this.fileTransport = new (transports.File)(
    {
        level: 'info',
        filename: `./log/${config.name}.log`,
        handleExceptions: true,
        maxsize: 5242880, //5MB,
        maxFiles: 5,
        prettyPrint: true,
        colorize: false
    }
);
this.mongoTransport = new (transports.MongoDB)(
    {
        level: 'error',
        handleExceptions: true,
        silent: false,
        db: this.connectionString,
        //options: MongoDB connection parameters (optional, defaults to {poolSize: 2, autoReconnect: true}).
        collection: 'LogError',
        includeIds: false,
        storeHost: true,
        //label: Label stored with entry object if defined.
        //name: 'MongoLog' + name,
        //capped: In case this property is true, winston-mongodb will try to create new log collection as capped, defaults to false.
        //cappedSize: Size of logs capped collection in bytes, defaults to 10000000.
        //cappedMax: Size of logs capped collection in number of documents.
        tryReconnect: true,
        decolorize: false,
        //expireAfterSeconds: Seconds before the entry is removed. Works only if capped is not set.
    }
);


const options: any = {
    logger: WBA.logTransports(),
    templatingEngines: { strategy: 'in-process' },
    extensions: {
        express: { app: this.reportingApp, server: WBA.server().$httpsServer },
    },
    appPath: this.reportingRoute,
    mountOnAppPath: true
};
```
![image](https://user-images.githubusercontent.com/16235598/43480647-3e6badcc-94da-11e8-91f3-b89a6454266a.png)
![image](https://user-images.githubusercontent.com/16235598/43480704-6302cfee-94da-11e8-9dd8-016cb4f400e2.png)

2. About jsreport-images package:
I'm using the package like this: 
`this.jsreport.use(require('jsreport-images')());`
![image](https://user-images.githubusercontent.com/16235598/43480801-af17bc14-94da-11e8-9c07-13c80fea05b2.png)

3. About the jsreport-studio
![image](https://user-images.githubusercontent.com/16235598/43480944-06d592c8-94db-11e8-9ef8-4667a08541c7.png)
![image](https://user-images.githubusercontent.com/16235598/43480964-0ef1f0aa-94db-11e8-943e-dfe0b8d77931.png)
This error is caused by bodyParser urlencoded middleware, when using extended: false, the middleware uses querystring, when extended: true, it uses qs lib, so setting extended: true resolves the issue, but can impact other things on the app. Any idea how to internally fix the issue? Maybe just setting the content-type header for studio api requests.

Thank you very much for your time and your attention.

**Comment by bjrmatos** [comment]
> 1. My framework also uses winston with three transport methods, I'm trying to pass the transport list to jscore using the logger property:

(i don't see in your example, what is the result of `WBA.logTransports()` so i'm going to assume that you are passing a list of winsont transport instances) 

what you are passing to logger is not the format that we expect in the logger object, we don't expect that you pass winston transports instances, read this [section in the docs](https://jsreport.net/learn/configuration#logging-configuration) which explains the format. and read [this other one](https://github.com/jsreport/jsreport-core/#logging) if you want to configure the transports manually using winston api.



> 2.- About jsreport-images package:
> I'm using the package like this:
> this.jsreport.use(require('jsreport-images')());

jsreport-images is deprecated, it is mentioned in [online docs](https://jsreport.net/learn/images) but it was not mentioned in github repository, i updated the README of jsreport-images to add the deprecation there too. you should use [jsreport-assets](https://github.com/jsreport/jsreport-assets) instead


>3. About the jsreport-studio
>This error is caused by bodyParser urlencoded middleware, when using extended: false, the middleware uses querystring, when extended: true, it uses qs lib, so setting extended: true resolves the issue, but can impact other things on the app. Any idea how to internally fix the issue? Maybe just setting the content-type header for studio api requests.

i think you can easily make you app to not apply your instance of body-parser middleware to the jsreport express app, jsreport + jsreport-express comes with its own set of middleware that are designed to work as it is, as a standalone express app, if you add layers of middleware (like body-parser) in front of the jsreport app then you are breaking that encapsulation, just ensure that you don't apply the body parser middleware of your app to the jsreport express app (the express extension already has body-parser configured to work without issues in the context of the report server)

**Comment by gustavomassa** [comment]
> My framework also uses winston with three transport methods, I'm trying to pass the transport list to jscore using the logger property:
> (i don't see in your example, what is the result of WBA.logTransports() so i'm going to assume that you are passing a list of winsont transport instances)
> 
> what you are passing to logger is not the format that we expect in the logger object, we don't expect that you pass winston transports instances, read this section in the docs which explains the format. and read this other one if you want to configure the transports manually using winston api.

The return is an array of winston transport instances:
```
this.consoleTransport = new (transports.Console)(
    {
        level: 'debug',
        handleExceptions: true,
        prettyPrint: true,
        colorize: true
    }
);
this.fileTransport = new (transports.File)(
    {
        level: 'info',
        filename: `./log/${config.name}.log`,
        handleExceptions: true,
        maxsize: 5242880, //5MB,
        maxFiles: 5,
        prettyPrint: true,
        colorize: false
    }
);
this.mongoTransport = new (transports.MongoDB)(
    {
        level: 'error',
        handleExceptions: true,
        silent: false,
        db: this.connectionString,
        //options: MongoDB connection parameters (optional, defaults to {poolSize: 2, autoReconnect: true}).
        collection: 'LogError',
        includeIds: false,
        storeHost: true,
        //label: Label stored with entry object if defined.
        //name: 'MongoLog' + name,
        //capped: In case this property is true, winston-mongodb will try to create new log collection as capped, defaults to false.
        //cappedSize: Size of logs capped collection in bytes, defaults to 10000000.
        //cappedMax: Size of logs capped collection in number of documents.
        tryReconnect: true,
        decolorize: false,
        //expireAfterSeconds: Seconds before the entry is removed. Works only if capped is not set.
    }
);
```
Any chance to add a new logger interface to accept transport instances as well? Since I have a singleton log controller class with custom log formats, I would like to use them for the entire process. I can help you with that.

**Comment by bjrmatos** [comment]
> Any chance to add a new logger interface to accept transport instances as well? Since I have a singleton log controller class with custom log formats, I would like to use them for the entire process. I can help you with that.

hmm but how is that different than adding the transports by yourself using winston's logger api that we expose? after you create the jsreport core instance `jsreportCreator(options)` you can access the logger with: `this.jsreport.logger` which is a winston logger instance where you can add transports by yourself, you can add there all the transports that you want using `this.jsreport.logger.add(...)`, just be aware of the [specific winston version](https://github.com/jsreport/jsreport-core/blob/master/package.json#L39) that we are using in order to check its docs correctly and know how to use its logger api correctly.

**Comment by gustavomassa** [comment]
You are correct, that is what I'm trying to find out, why the interfaces are different, it should be the same.
You are using     
"winston": "2.4.0",
"winston-transport": "3.0.1"

I'm using
"winston": "^3.0.0"
 "winston-mongodb": "^4.0.0-rc1"
"@types/winston": "^2.3.8"

hmm I don't use the winston-transport package, this is how I create the logger with the transport list:
```
const { createLogger, format, transports } = require('winston');
const { combine, timestamp, label, printf } = format;
require('winston-mongodb');

class LogController {
    private mainLogger: any;
    private connectionString: string;
    private consoleTransport: object;
    private fileTransport: object;
    private mongoTransport: object;
    private transportList: Array<object>;


    constructor() {
        this.consoleTransport = new (transports.Console)(
            {
                level: 'debug',
                handleExceptions: true,
                prettyPrint: true,
                colorize: true
            }
        );
        this.fileTransport = new (transports.File)(
            {
                level: 'info',
                filename: `./log/${config.name}.log`,
                handleExceptions: true,
                maxsize: 5242880, //5MB,
                maxFiles: 5,
                prettyPrint: true,
                colorize: false
            }
        );
        this.mongoTransport = new (transports.MongoDB)(
            {
                level: 'error',
                handleExceptions: true,
                silent: false,
                db: this.connectionString,
                //options: MongoDB connection parameters (optional, defaults to {poolSize: 2, autoReconnect: true}).
                collection: 'LogError',
                includeIds: false,
                storeHost: true,
                //label: Label stored with entry object if defined.
                //name: 'MongoLog' + name,
                //capped: In case this property is true, winston-mongodb will try to create new log collection as capped, defaults to false.
                //cappedSize: Size of logs capped collection in bytes, defaults to 10000000.
                //cappedMax: Size of logs capped collection in number of documents.
                tryReconnect: true,
                decolorize: false,
                //expireAfterSeconds: Seconds before the entry is removed. Works only if capped is not set.
            }
        );
        this.transportList = new Array<object>();
        this.transportList.push(this.consoleTransport);
        this.transportList.push(this.fileTransport);
    }

    private setMasterLabel(): void {
        this.mainLogger.format = combine(
            label({ label: `Master PID ${process.pid}` }),
            timestamp(),
            this.logFormat
        );
    }

    private logFormat = printf(info => {
        return `${info.timestamp} [${info.label}] ${info.level}: ${info.message}`;
    });

    private initWinston(): void {
        try {
            this.mainLogger = createLogger({
                transports: this.transportList,
                exitOnError: false
            });
            this.setMasterLabel();
        } catch (ex) {
            console.log('Failed to init log system: ', new Error(ex));
        }
    }
}
```

I'm using the createLogger interface, passing the array of transports directly.
There are important changes on the winston API regarding version 2.x to version 3.
https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md
