### ISSUE TITLE
Error handling middle ware is running before extensions code 

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport-express#4]
If the extension adds an api endpoint like this

```js
this.reporter.on('express-configure', () => {
  app.get('/reports/:id/content', function (req, res, next) {
      serveReport(req, res).then(function (result) {
        result.stream.pipe(res)
      }).catch(next)
  })
}
```

Calling the next actually doesn't reach our express error middle ware and uses the default one, because we add the middle ware before emitting `express-configure`. I guess we should add it afterwards instead.

**Comment by bjrmatos** [comment]
done
