### ISSUE TITLE
add and option to set express "trust proxy" application settings

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport-express#5]
add a way to enable `trust proxy` in [express application settings](http://expressjs.com/en/api.html#app.settings.table), to have better support when jsreport is running [behind proxies](http://expressjs.com/en/guide/behind-proxies.html).

also we need to change this [line](https://github.com/jsreport/jsreport-express/blob/master/lib/reporter.express.js#L57) to [req.hostname](http://expressjs.com/en/api.html#req.hostname)

**Comment by pofider** [comment]
>add a way to enable trust proxy in express application settings, to have better support when jsreport is running behind proxies.

we have this randomly in extensions:
https://github.com/jsreport/jsreport-assets/blob/master/lib/assets.js#L215

it should be set in this extension just once

> also we need to change this line to req.hostname

yes

**Comment by pofider** [comment]
The express extension now exposes `req.context.http.baseUrl`. This is used by extensions so there is no need to deal with the proxy there.

The express extension now enables proxy in case `reporter.options.express.trusyProxy !== false`
