### ISSUE TITLE
appPath not applied to express server

### ISSUE THREAD

**Issue by sguesdon** [jsreport/jsreport-express#8]
express server not apply appPath option.

> appPath (string) - optionally set application path, if you run application on http://appdomain.com/reporting then set /reporting to appPath

doc: https://jsreport.net/learn/configuration#web-server-configuration

**Comment by bjrmatos** [comment]
hi @sguesdon, `appPath` is designed to be used when you proxy things to your app, like for example when you have a domain and want that `http://appdomain.com/reporting` goes to one of your apps (jsreport) and other route like `http://appdomain.com/app` goes to another app (your business app). it is more about when you are using a proxy like nginx that is setup to route things to specific process (server ports) in your machine, the `appPath` is useful there to let know jsreport what is the starting part of the original request. 

that said, what you thought is the intended case for `appPath` (mounting jsreport app over some subpath) can be achieved by following [these instructions](https://jsreport.net/learn/adapting-jsreport#attach-to-existing-express-app), then in your code you can mount jsreport app under `jsreport.use('/reporting', jsreportApp)` or some other path that you like.

we are in the process to revamp docs about `appPath` to explain better the use case for it and when to use it.

**Comment by Nydareld** [comment]
( sorry for my english we are french :fr: ) 
If i remembre, the issue we had, is that when we set appPath=jsreport, to proxy the requests, the studio is well rendered at the http://our.domain.fr/jsreport/, but the express api points reply "cannot GET /jsreport"

**Comment by pofider** [comment]
@Nydareld  Does your proxy rewrite url `/jsreport` to `/`? This is needed.

We cannot accept the PR because I believe it is breaking change. However I understand that it would be nice if it would be possible to configure jsreport to run on subpath without need for url rewrites. 
We have open issue to analyse here: jsreport/jsreport#422

Thank you for your afford here. We will very likely use the code just with different config prop name to make it non breaking. Lets see.

**Comment by Nydareld** [comment]
effectively our proxy does not suports url re-writing. ( it has already make issues in the past ) 
We can edit the PR with another prop name, it's a good idea.

**Comment by sguesdon** [comment]
hi, 
i changed the name of the prop in pr #9

**Comment by bjrmatos** [comment]
i made some comments in the PR #9

**Comment by bjrmatos** [comment]
as described in #9 comments, we added new option `mountOnAppPath` to help with your case. the exact changes are [here](https://github.com/jsreport/jsreport-express/commit/b63e5bbea3e04c45412779807c7562ca23b99c70) and the new option is published in version `2.2.0`, so you can try it in your project.

**Comment by sguesdon** [comment]
Thx,
